### ISSUE TITLE
[Feature Request]: proto 文件能否分离成单独的仓库？

### ISSUE THREAD

**Issue by JustAnotherID** [whitechi73/kritor#1]
目前对接 kritor 时需要手动拷贝 proto 文件，能否将其独立出来便于下游直接使用 git submodule 进行引用？

**Comment by Simplxss** [comment]
protos 已分离至 [kritor](https://github.com/KarinJS/kritor)

另外问一句 您打算接入的语言是什么

**Comment by JustAnotherID** [comment]
> protos 已分离至 [kritor](https://github.com/KarinJS/kritor)

看到了，非常感谢。

> 另外问一句 您打算接入的语言是什么

golang
